services:
  kiez-design-api:
    build: .
    container_name: kiez-design-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "3100:3100"
    volumes:
      - ./storage:/app/storage
